---
title: "Iris Model Building"
author: "Mike Calabro"
format: html
editor: visual
execute: 
  warning: FALSE
  message: FALSE
---

## The Data

```{r}
library(tidyverse)
library(tidymodels)
library(janitor)
library(kableExtra)
library(rpart.plot)
tidymodels_prefer()

iris <- iris %>% clean_names()

iris %>%
  slice(47:53) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

## Creating Training/Test Sets of Data

```{r}
set.seed(617)
iris_split <- initial_split(iris, prop = 0.8)
iris_train <- training(iris_split)
iris_test <- testing(iris_split)

iris_folds <- vfold_cv(iris_train)
```

## Fitting a Decision Tree

```{r}
tree_spec <- 
  decision_tree(tree_depth = 6, min_n = 18) %>%
  set_engine('rpart') %>%
  set_mode('classification')

tree_recipe <-
  recipe(species ~ ., data = iris_train)

tree_workflow <- 
  workflow() %>%
  add_model(tree_spec) %>%
  add_recipe(tree_recipe)

keep_pred <- control_resamples(save_pred = TRUE, save_workflow = TRUE)

tree_res <- tree_workflow %>% fit_resamples(resamples = iris_folds, control = keep_pred)

collect_metrics(tree_res)

tree_fit <- fit(tree_workflow, iris_train)

tree_fit

rpart.plot(tree_fit$fit$fit$fit)
```

```{r}
tree_pred <- predict(tree_fit, iris_test)

iris_test <- 
  iris_test %>%
  cbind(tree_pred)

iris_test

table(iris_test$species, iris_test$.pred_class)
mean(iris_test$species == iris_test$.pred_class)
```
